"""Offscreen UI gates and worker-boundary tests; no provider or KiCad writes."""
import gc
import os
os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
import tempfile
import threading
import time
import unittest
from dataclasses import replace
from pathlib import Path
from unittest.mock import Mock, patch
from types import SimpleNamespace

try:
    from PySide6.QtWidgets import QApplication
    from PySide6.QtCore import Qt
    from velatrace.ui import MainWindow, ComponentCard, FindingCard, RouteCanvas
except ImportError:
    QApplication = None

from velatrace.audit import AuditStage
from velatrace.flags import Function, Flag
from velatrace.models import Component
from velatrace.provider import ProviderError
from velatrace.ses import RoutePlan, Track


@unittest.skipIf(QApplication is None, "Install the pinned Qt UI dependency")
class UiTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.app = QApplication.instance() or QApplication([])

    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.window = MainWindow(demo=True, config_dir=Path(self.temp.name))

    def test_save_report_writes_html(self):
        target = Path(self.temp.name) / "out.html"
        with patch("velatrace.ui.QFileDialog.getSaveFileName", return_value=(str(target), "")):
            self.window.export_report()
        html = target.read_text(encoding="utf-8")
        self.assertIn("Generated by VelaTrace", html)
        self.assertEqual(self.window.status.text(), "Report saved.")

    def tearDown(self):
        self.window.safety = None
        self.wait_idle()
        self.window.close()
        self.app.processEvents()
        # Collect the closed window here, on the Qt thread: the window's own callbacks
        # form reference cycles, and cyclic GC on a worker thread would abort Qt.
        self.window.deleteLater()  # free Qt objects on the Qt thread before GC
        self.window = None
        gc.collect()
        self.temp.cleanup()

    def wait_idle(self):
        deadline = time.monotonic() + 5
        while self.window.worker is not None and time.monotonic() < deadline:
            self.app.processEvents()
            time.sleep(.005)
        self.assertIsNone(self.window.worker)
        self.app.processEvents()

    def wait_drc(self):
        deadline = time.monotonic() + 5
        while (self.window._drc_pending or self.window.worker is not None) and time.monotonic() < deadline:
            self.app.processEvents()
            time.sleep(.005)
        self.assertEqual(self.window._drc_pending, 0)
        self.wait_idle()

    def test_model_and_board_text_never_becomes_html(self):
        card = ComponentCard(Component("<b>R1</b>", "<img src=x>", "test", ()),
                             Function("<a href=evil>click</a>", "role", 1))
        labels = card.findChildren(__import__("PySide6.QtWidgets", fromlist=["QLabel"]).QLabel)
        self.assertTrue(all(item.textFormat() == Qt.TextFormat.PlainText for item in labels))
        self.assertTrue(any("<a href=evil>" in item.text() for item in labels))

    def test_all_service_jobs_share_one_worker_and_results_return_to_ui_thread(self):
        threads, callbacks = [], []
        for _ in range(2):
            self.window.run_work("test", lambda usage: threads.append(threading.get_ident()),
                                 lambda value: callbacks.append(threading.get_ident()))
            self.wait_idle()
        self.assertEqual(threads[0], threads[1])
        self.assertNotEqual(threads[0], threading.get_ident())
        self.assertEqual(callbacks, [threading.get_ident()] * 2)

    def test_refused_privacy_notice_never_starts_inference(self):
        self.window.audit.stage = AuditStage.FUNCTIONS
        self.window.settings.model = "test-model"
        with patch("velatrace.ui.ask", return_value=False), patch.object(self.window.audit, "infer_functions") as infer:
            self.window.audit_next()
            infer.assert_not_called()
            self.assertIsNone(self.window.worker)

    def test_consent_survives_new_store_and_endpoint_change_reprompts(self):
        from velatrace.privacy import ConsentStore
        from velatrace.ui import Settings
        self.assertNotIn("test-secret", repr(Settings(key="test-secret")))
        with patch("velatrace.ui.ask", return_value=True) as notice:
            self.assertTrue(self.window.authorize_provider())
            notice.assert_called_once()
        self.window.consent = ConsentStore(Path(self.temp.name) / "privacy-consent.json")
        with patch("velatrace.ui.ask", return_value=False) as notice:
            self.assertTrue(self.window.authorize_provider())
            notice.assert_not_called()
            self.window.audit.provider.config = replace(self.window.audit.provider.config,
                                                       endpoint="https://elsewhere.invalid/v1")
            self.assertFalse(self.window.authorize_provider())
            notice.assert_called_once()

    def test_pricing_failure_is_visible_without_expanding_card(self):
        self.window.audit.flags = [Flag("U3", "Review duplicate sensor")]
        self.window.audit.provider.config = replace(self.window.audit.provider.config,
                                                   protocol="openai", builtin_search=True)
        with patch("velatrace.ui.ask", return_value=True), patch.object(
                self.window.audit.provider, "complete",
                side_effect=ProviderError("Provider rejected the API key or permission.")) as complete:
            # A click whose estimate differs from the shown line only refreshes the line.
            self.window.price_parts()
            complete.assert_not_called()
            self.assertIsNone(self.window.worker)
            self.assertIn("Pricing 1 flagged: ≤1 calls", self.window.cost_line.text())
            self.window.price_parts()  # the click on the shown estimate is the consent
            self.wait_idle()
        self.assertIn("1 pricing search(es) failed", self.window.totals.text())
        self.assertIn("API key or permission", self.window.status.text())
        self.assertTrue(self.window.pricing.prices["U3"].estimated)
        self.assertTrue(self.window.cards["U3"].details.isHidden())

    def test_confirm_applies_edits_and_classification_waits_for_its_own_click(self):
        audit = self.window.audit
        audit.stage = AuditStage.REVIEW_FUNCTIONS
        self.window.render_cards()
        self.window.cards["U1"].function_edit.setText("Corrected MCU role")
        estimate = SimpleNamespace(input_tokens=1234, output_cap=4096, calls_max=3, method="exact",
                                   confirmation_fingerprint="fp")
        with patch("velatrace.ui.ask") as asked, patch.object(self.window, "authorize_provider", return_value=True), \
                patch.object(audit, "estimate_classification", return_value=estimate) as count, \
                patch.object(audit, "classify") as classify:
            self.window.audit_next()  # inline Confirm functions: no dialog
            self.wait_idle()
            self.assertEqual(audit.functions["U1"].text, "Corrected MCU role")
            self.assertEqual(audit.stage, AuditStage.CONFIRMED_FUNCTIONS)
            count.assert_called_once()
            classify.assert_not_called()  # the estimate is shown, not acted on
            self.assertIn("1,234 tokens", self.window.cost_line.text())
            self.assertEqual(self.window.next_button.text(), "Classify parts")
            audit.stage, audit.estimate = AuditStage.CLASSIFICATION_ESTIMATE, estimate
            self.window.audit_next()
            self.wait_idle()
            classify.assert_called_once()
            self.assertEqual(classify.call_args.args[0], "fp")
        asked.assert_not_called()

    def test_accepted_setup_retires_old_provider_even_when_router_check_fails(self):
        from PySide6.QtWidgets import QDialog
        from velatrace.errors import CapabilityError
        from velatrace.ui import SettingsDialog
        new_settings = replace(self.window.settings, model="replacement-model", key="synthetic-new-key")
        old_audit = self.window.audit
        safety = SimpleNamespace(clear_preview=lambda: None)
        self.window.safety = safety
        with patch.object(SettingsDialog, "exec", return_value=QDialog.DialogCode.Accepted), \
                patch.object(SettingsDialog, "value", return_value=new_settings), \
                patch("velatrace.ui.Freerouting.check_startup", side_effect=CapabilityError("Router missing")):
            self.window.configure()
            self.wait_idle()
        self.assertIsNone(self.window.audit)
        self.assertIsNone(self.window.pricing)
        self.assertIs(self.window.safety, safety)
        self.assertFalse(self.window.description.isReadOnly())
        self.assertFalse(self.window.next_button.isEnabled())
        self.assertIn("Router missing", self.window.status.text())
        replacement = self.window.make_audit()
        self.assertIsNot(replacement, old_audit)
        self.assertEqual(replacement.provider.config.model, "replacement-model")
        self.assertEqual(replacement.provider.config.api_key, "synthetic-new-key")

    def test_setup_cleanup_failure_retains_safety_handle_but_not_old_provider(self):
        from PySide6.QtWidgets import QDialog
        from velatrace.ui import SettingsDialog
        def fail_cleanup():
            raise RuntimeError("Cleanup refused")
        safety = SimpleNamespace(clear_preview=fail_cleanup)
        self.window.safety = safety
        with patch.object(SettingsDialog, "exec", return_value=QDialog.DialogCode.Accepted), \
                patch("velatrace.ui.Freerouting.check_startup") as startup:
            self.window.configure()
            self.wait_idle()
        startup.assert_not_called()
        self.assertIs(self.window.safety, safety)
        self.assertIsNone(self.window.audit)
        self.assertIn("Cleanup refused", self.window.status.text())

    def test_pending_prompt_prevents_routing(self):
        self.window.route_prompt.setText("keep traces away from headers")
        self.window.routing = SimpleNamespace()
        with patch("velatrace.ui.ask") as ask:
            self.window.route()
        ask.assert_not_called()
        self.assertIn("pending rule", self.window.status.text())
        self.window.routing = None

    def ready_route_preview(self):
        from velatrace.dsn import DsnInput, ExportTicket, file_digest
        from velatrace.routing import RoutingSession, RoutingStage, ValidationReport, plan_digest
        board = Path(self.temp.name) / "board.kicad_pcb"
        board.write_text("synthetic board")
        path = Path(self.temp.name) / "board.dsn"
        path.write_text("synthetic DSN")
        dsn = DsnInput(path, file_digest(path), ExportTicket.begin(board),
                       frozenset({"N"}), frozenset({"F.Cu", "B.Cu"}))
        router, validator, writer = Mock(), Mock(), Mock()
        validator.supports.return_value = True
        session = RoutingSession(self.window.constraints, router, validator)
        session.command("/autoroute")
        session.set_input(dsn, all_footprints_placed=True)
        session.confirm_constraints(self.window.constraints.fingerprint)
        session.plan = RoutePlan("board", (Track("N", "B.Cu", .25, ((1, 2), (3, 4))),), ())
        session.report = ValidationReport(plan_digest(session.plan), 0, 0, board_digest=dsn.ticket.board_digest)
        session.stage = RoutingStage.PREVIEW
        self.window.routing, self.window.writer = session, writer
        self.window.safety = Mock()
        self.window.preview_shown = True
        self.window.canvas.plan = session.plan
        self.window.pages.setCurrentIndex(1)
        self.window.refresh_actions()
        return session, router, validator, writer

    def test_approve_button_applies_once_without_regenerating_preview(self):
        from velatrace.routing import RoutingStage
        session, router, validator, writer = self.ready_route_preview()
        with patch("velatrace.ui.ask") as asked:
            self.window.approve_button.click()  # the click is the confirmation
            self.wait_idle()
        asked.assert_not_called()
        writer.apply.assert_called_once_with(session.input, session.plan, session.report, drc_override=False)
        router.route.assert_not_called()
        validator.validate.assert_not_called()
        self.window.safety.show_preview.assert_not_called()
        self.assertEqual(session.stage, RoutingStage.APPROVED)
        self.assertIsNone(self.window.canvas.plan)
        self.assertFalse(self.window.preview_shown)
        self.assertFalse(self.window.approve_button.isEnabled())
        self.assertIn("Applied 1 copper track segments and 0 vias on B.Cu", self.window.canvas.toolTip())
        self.assertIn("Applied 1 copper", self.window.canvas.accessibleDescription())
        self.assertTrue(self.window.route_summary.isHidden())

    def start_route(self, validate=None, snapshot="snapshot"):
        """Click Generate; returns once the preview is shown, with DRC gated on `release`."""
        from velatrace.routing import ValidationReport, plan_digest
        session, router, validator, writer = self.ready_route_preview()
        router.route.return_value = """(session board (base_design board.dsn)
            (routes (resolution um 10) (network_out
            (net N (wire (path F.Cu 2500 10000 20000 30000 40000))))))"""
        release = threading.Event()
        self.addCleanup(release.set)
        def gated(dsn, plan, constraints):
            # Never capture `self` here: a TestCase<->window reference cycle lets Python's
            # cyclic GC destroy the window's widgets later on a worker thread, which aborts Qt.
            if not release.wait(5):
                raise AssertionError("DRC gate was never released")
            if validate:
                return validate(dsn, plan, constraints)
            return ValidationReport(plan_digest(plan), 0, 0, board_digest=dsn.ticket.board_digest)
        validator.validate.side_effect = gated
        validator.evidence = (None, None, None, None, None, snapshot)
        self.window.validator = validator
        self.window.safety.show_preview.return_value = "snapshot"
        # The live-board export has its own tests; here it yields the exported snapshot.
        self.window.prepare_board = lambda cancel: ("exported", ["Note: edge rule."])
        with patch("velatrace.ui.ask", return_value=True), patch("velatrace.ui.trusted_via_catalog", return_value={}):
            self.window.route_button.click()
            self.wait_idle()
        return session, router, validator, writer, release

    def test_preview_shows_before_drc_and_approval_waits_for_it(self):
        from velatrace.routing import RoutingStage
        session, router, validator, writer, release = self.start_route()
        # Preview drawn (no expected board: DRC has not run yet); approval still locked.
        router.route.assert_called_once()
        self.window.safety.show_preview.assert_called_once_with(session.input, session.plan, "exported")
        self.assertIs(self.window.canvas.plan, session.plan)
        self.assertEqual(session.stage, RoutingStage.VALIDATING)
        self.assertFalse(self.window.approve_button.isEnabled())
        self.assertFalse(self.window.approve_anyway_button.isEnabled())
        self.assertTrue(self.window.route_page.isEnabled())  # reroute/reject stay usable
        self.assertIn("Checking DRC", self.window.status.text())
        release.set()
        self.wait_drc()
        validator.validate.assert_called_once()
        writer.apply.assert_not_called()
        self.assertEqual(session.stage, RoutingStage.PREVIEW)
        self.assertTrue(self.window.approve_button.isEnabled())
        self.assertFalse(self.window.approve_anyway_button.isEnabled())
        summary = self.window.canvas.toolTip()
        self.assertIn("Preview only", summary)
        self.assertIn("Approve and apply copper", summary)
        self.assertRegex(summary, r"Routing \d+\.\ds; preview \d+\.\ds; DRC \d+\.\ds")

    def test_reject_or_reroute_during_drc_discards_the_stale_result(self):
        from velatrace.routing import RoutingStage
        session, router, validator, writer, release = self.start_route()
        self.window.reason.setText("Wrong side of the board")
        self.window.reject_button.click()
        self.wait_idle()
        self.assertEqual(session.stage, RoutingStage.REJECTED)
        self.window.safety.clear_preview.assert_called_once()
        release.set()
        self.wait_drc()
        validator.validate.assert_called_once()
        self.assertEqual(session.stage, RoutingStage.REJECTED)
        self.assertIsNone(session.report)
        self.assertFalse(self.window.approve_button.isEnabled())
        self.assertIn("Rejected: Wrong side", self.window.canvas.toolTip())
        # Reroute while the first DRC is still running: only the newest result counts.
        session, router, validator, writer, release = self.start_route()
        first = session.plan
        with patch("velatrace.ui.ask", return_value=True), patch("velatrace.ui.trusted_via_catalog", return_value={}):
            self.window.route_button.click()
            self.wait_idle()
        self.assertIsNot(session.plan, first)
        release.set()
        self.wait_drc()
        self.assertEqual(validator.validate.call_count, 2)
        self.assertEqual(session.stage, RoutingStage.PREVIEW)
        self.assertEqual(session.report.plan_digest, __import__("velatrace.routing", fromlist=["plan_digest"]).plan_digest(session.plan))

    def test_drc_failure_or_board_change_removes_preview_and_blocks_approval(self):
        from velatrace.errors import ValidationError
        from velatrace.routing import RoutingStage
        def fail(*args):
            raise ValidationError("KiCad CLI failed (exit 3)")
        for kwargs, message in (({"validate": fail}, "KiCad CLI failed"),
                                ({"snapshot": "other board"}, "board changed after the preview")):
            with self.subTest(message=message):
                session, router, validator, writer, release = self.start_route(**kwargs)
                release.set()
                self.wait_drc()
                self.assertEqual(session.stage, RoutingStage.SETUP)
                self.assertFalse(self.window.preview_shown)
                self.assertIsNone(self.window.canvas.plan)
                self.window.safety.clear_preview.assert_called_once()
                self.assertFalse(self.window.approve_button.isEnabled())
                self.assertFalse(self.window.approve_anyway_button.isEnabled())
                self.assertIn(message, self.window.status.text())
                self.assertIn(message, self.window.route_summary.text())

    def test_approve_anyway_confirms_drc_items_with_cancel_default(self):
        from PySide6.QtWidgets import QMessageBox
        from velatrace.routing import RoutingStage
        session, router, validator, writer = self.ready_route_preview()
        reasons = tuple(f"kind {n} (error): 1" for n in range(7))
        session.report = replace(session.report, drc_violations=7, blocking_reasons=reasons)
        self.window.refresh_actions()
        self.assertFalse(self.window.approve_button.isEnabled())
        self.assertTrue(self.window.approve_anyway_button.isEnabled())
        self.assertNotEqual(self.window.approve_anyway_button.objectName(), "primary")
        seen = []
        def exec_(box, answer):
            seen.append((box.defaultButton() is box.button(QMessageBox.StandardButton.Cancel), box.text()))
            return answer
        with patch.object(QMessageBox, "exec", lambda box: exec_(box, QMessageBox.StandardButton.Cancel)):
            self.window.approve_anyway_button.click()
            self.wait_idle()
        writer.apply.assert_not_called()
        cancel_default, text = seen[0]
        self.assertTrue(cancel_default)
        self.assertIn("7 blocking issue", text)
        self.assertIn("kind 0 (error): 1", text)
        self.assertIn("kind 4 (error): 1", text)
        self.assertNotIn("kind 5", text)
        self.assertIn("and 2 more", text)
        self.assertIn("DESPITE", text)
        with patch.object(QMessageBox, "exec", lambda box: exec_(box, QMessageBox.StandardButton.Ok)):
            self.window.approve_anyway_button.click()
            self.wait_idle()
        writer.apply.assert_called_once_with(session.input, session.plan, session.report, drc_override=True)
        self.assertEqual(session.stage, RoutingStage.APPROVED)
        self.assertIn("despite 7 DRC issue(s)", self.window.canvas.toolTip())
        self.assertFalse(self.window.approve_anyway_button.isEnabled())

    def test_drc_findings_offer_approve_anyway_after_background_check(self):
        from velatrace.routing import ValidationReport, plan_digest
        def violations(dsn, plan, constraints):
            return ValidationReport(plan_digest(plan), 2, 0, board_digest=dsn.ticket.board_digest,
                                    blocking_reasons=("clearance (error): 2",))
        session, router, validator, writer, release = self.start_route(violations)
        self.assertFalse(self.window.approve_anyway_button.isEnabled())
        release.set()
        self.wait_drc()
        self.assertFalse(self.window.approve_button.isEnabled())
        self.assertTrue(self.window.approve_anyway_button.isEnabled())
        summary = self.window.route_summary.text()
        self.assertIn("Approval blocked: clearance (error): 2", summary)
        self.assertIn("Approve anyway", summary)

    def test_approve_anyway_is_never_offered_for_shortfall(self):
        from velatrace.routing import RoutingStage
        session, *_ = self.ready_route_preview()
        session.report = replace(session.report, drc_violations=1, unconnected_count=2)
        session.stage = RoutingStage.SHORTFALL
        self.window.refresh_actions()
        self.assertFalse(self.window.approve_button.isEnabled())
        self.assertFalse(self.window.approve_anyway_button.isEnabled())

    def test_preview_layer_refusal_happens_before_freerouting(self):
        from velatrace.errors import ValidationError
        session, router, validator, writer = self.ready_route_preview()
        safety = self.window.safety
        safety.prepare_preview.side_effect = ValidationError("User.9 has 1 dashed 0.1 mm line")
        self.window.prepare_board = lambda cancel: (safety.prepare_preview(), (None, []))[1]
        with patch("velatrace.ui.ask", return_value=True):
            self.window.route_button.click()
            self.wait_idle()
        router.route.assert_not_called()
        validator.validate.assert_not_called()
        self.window.safety.show_preview.assert_not_called()
        self.assertIn("User.9 has 1 dashed", self.window.status.text())

    def test_cancel_kills_routing_and_writes_nothing(self):
        from velatrace.errors import RoutingCancelled
        session, router, validator, writer = self.ready_route_preview()
        def route(dsn, constraints):  # Stands in for Freerouting: runs until its event is set.
            if not router.cancel.wait(5):
                raise AssertionError("Cancel never reached the router")
            raise RoutingCancelled("Cancelled; nothing was written to the board.")
        router.route.side_effect = route
        self.window.prepare_board = lambda cancel: ("exported", [])
        with patch("velatrace.ui.trusted_via_catalog", return_value={}):
            self.window.route_button.click()
            deadline = time.monotonic() + 5
            while not self.window.cancel_button.isVisibleTo(self.window) and time.monotonic() < deadline:
                self.app.processEvents()
            self.window.cancel_button.click()
            self.wait_idle()
        self.window.safety.show_preview.assert_not_called()
        writer.apply.assert_not_called()
        validator.validate.assert_not_called()
        self.assertEqual(session.stage.value, "setup")
        self.assertIn("Cancelled; nothing was written", self.window.status.text())
        self.assertFalse(self.window.cancel_button.isVisibleTo(self.window))

    def test_cancel_during_drc_discards_the_check_and_removes_the_preview(self):
        session, router, validator, writer, release = self.start_route()
        self.assertTrue(self.window.cancel_button.isVisibleTo(self.window))
        self.window.cancel_button.click()
        self.wait_idle()
        self.window.safety.clear_preview.assert_called_once()
        release.set()
        self.wait_drc()
        self.assertIsNone(session.report)
        self.assertFalse(self.window.approve_button.isEnabled())
        self.assertIn("Cancelled; the board is unchanged", self.window.canvas.toolTip())

    def test_export_failure_offers_the_manual_dsn_path(self):
        from velatrace.errors import ExportUnavailable
        session, router, validator, writer = self.ready_route_preview()
        board = Path(self.temp.name) / "board.kicad_pcb"
        board.write_text('(kicad_pcb (gr_rect (start 0 0) (end 40 30) (layer "Edge.Cuts")))', encoding="utf-8")
        board.with_suffix(".kicad_pro").write_text('{"board": {"design_settings": {}}}', encoding="utf-8")
        snapshot = SimpleNamespace(path=board, components=())
        self.window.snapshot = snapshot
        self.window.safety.board.get_as_string.return_value = board.read_text(encoding="utf-8")
        self.window.validator = validator
        validator.cli.export_dsn.side_effect = ExportUnavailable("no pcbnew module.")
        reader = SimpleNamespace(read_board=lambda: snapshot, version=(10, 0, 6),
                                 client=SimpleNamespace(get_board=lambda handle=self.window.safety.board: handle))
        with patch("velatrace.ui.KiCadReader.connect", return_value=reader):
            self.window.route_button.click()
            self.wait_idle()
        router.route.assert_not_called()
        self.assertIsNotNone(self.window.ticket)
        self.assertTrue(self.window.import_button.isVisibleTo(self.window))
        self.assertIn("Specctra DSN", self.window.route_summary.text())
        self.assertIn("no pcbnew module", self.window.status.text())

    def test_failed_approval_keeps_preview_and_reports_unconfirmed_copper(self):
        from velatrace.errors import ValidationError
        from velatrace.write_safety import UncertainWriteError
        for failure in (ValidationError("Board changed; export again"),
                        UncertainWriteError("IPC commit result is uncertain; do not retry")):
            with self.subTest(failure=type(failure).__name__):
                session, router, validator, writer = self.ready_route_preview()
                writer.apply.side_effect = failure
                with patch("velatrace.ui.ask", return_value=True):
                    self.window.approve_button.click()
                    self.wait_idle()
                writer.apply.assert_called_once()
                router.route.assert_not_called()
                validator.validate.assert_not_called()
                self.window.safety.show_preview.assert_not_called()
                self.assertIs(self.window.canvas.plan, session.plan)
                self.assertTrue(self.window.preview_shown)
                self.assertIn("Copper application was not confirmed", self.window.route_summary.text())
                self.assertIn(str(failure), self.window.route_summary.text())
                self.assertIn(str(failure), self.window.status.text())

    def test_worker_stage_and_elapsed_status_stop_after_completion(self):
        gate = threading.Event()
        self.addCleanup(gate.set)
        def operation(_):
            self.window.executor.progress.emit("Checking candidate DRC")
            gate.wait(3)
        self.window.run_work("Routing copper paths", operation)
        deadline = time.monotonic() + 2
        while "Checking candidate DRC" not in self.window.status.text() and time.monotonic() < deadline:
            self.app.processEvents()
            time.sleep(.005)
        self.window._work_started -= 2
        self.window.update_work_status()
        self.assertRegex(self.window.status.text(), r"Checking candidate DRC · [2-9]s")
        gate.set()
        self.wait_idle()
        self.assertFalse(self.window.work_timer.isActive())
        self.assertEqual(self.window.status.text(), "Ready.")

    def test_route_approval_is_reachable_in_a_small_window(self):
        self.ready_route_preview()
        self.window.blocking("A detailed validation warning for review. " * 40)
        self.window.resize(700, 650)
        self.window.show()
        self.app.processEvents()
        self.assertLessEqual(self.window.height(), 650)
        self.window.route_scroll.ensureWidgetVisible(self.window.approve_button)
        self.app.processEvents()
        viewport = self.window.route_scroll.viewport()
        center = self.window.approve_button.mapTo(viewport, self.window.approve_button.rect().center())
        self.assertTrue(viewport.rect().contains(center))
        self.assertGreater(self.window.route_scroll.verticalScrollBar().value(), 0)
        self.assertTrue(self.window.approve_button.isEnabled())
        # Busy gating must disable the inner controls even though the stack now
        # contains a scroll area around them.
        self.window.worker = self.window.executor
        try:
            self.window.refresh_actions()
            self.assertFalse(self.window.route_page.isEnabled())
            self.assertFalse(self.window.approve_button.isEnabled())
        finally:
            self.window.worker = None
            self.window.refresh_actions()

    def test_cleanup_failure_keeps_window_and_safety_handle(self):
        class Safety:
            def clear_preview(self):
                raise RuntimeError("Backup refused")
        self.window.safety = Safety()
        self.window.show()
        self.window.close()
        self.wait_idle()
        self.assertTrue(self.window.isVisible())
        self.assertIsNotNone(self.window.safety)
        self.assertIn("Backup refused", self.window.status.text())
        self.assertIn("Close again", self.window.status.text())
        # A second close exits without a dialog instead of retrying forever.
        with patch("velatrace.ui.ask") as ask:
            self.window.close()
            self.wait_idle()
            self.app.processEvents()
        ask.assert_not_called()
        self.assertIsNone(self.window.safety)
        self.assertFalse(self.window.isVisible())

    def test_multilayer_canvas_renders_actual_polylines(self):
        canvas = RouteCanvas()
        canvas.resize(600, 240)
        canvas.plan = RoutePlan("board", (
            Track("VCC", "F.Cu", .25, ((1, 1), (5, 2), (8, 2))),
            Track("GND", "B.Cu", .25, ((1, 2), (7, 8))),), ())
        canvas.show()
        self.app.processEvents()
        self.assertFalse(canvas.grab().isNull())
        canvas.close()

    def test_findings_are_grouped_by_severity_and_expand_in_place(self):
        from PySide6.QtWidgets import QLabel
        headers = [item.text() for item in self.window.card_container.findChildren(QLabel)
                   if " · " in item.text() and item.text().split(" · ")[0] in {"Errors", "Warnings", "Savings", "Info"}]
        self.assertEqual(headers, ["Errors · 1", "Warnings · 3", "Savings · 1"])
        self.assertIn("1 error · 3 warnings · 1 saving · est. $0.01/board saving", self.window.totals.text())
        self.assertIn("never removed automatically", self.window.totals.toolTip())
        card = self.window.finding_cards[0]
        self.assertEqual(card.finding.severity.value, "error")
        self.assertTrue(card.details.isHidden())
        from PySide6.QtTest import QTest
        QTest.mouseClick(card, Qt.MouseButton.LeftButton)
        self.assertFalse(card.details.isHidden())
        self.assertIn("Fix:", card.details.text())

    def test_finding_text_is_plain_and_locate_hook_is_reserved(self):
        from decimal import Decimal
        from PySide6.QtWidgets import QLabel, QPushButton
        from velatrace.findings import Finding, Severity
        finding = Finding("x", Severity.SAVING, "<b>R1</b> <a href=evil>x</a>", ("R1",),
                          evidence="<img src=x>", fix="remove", cost_delta=Decimal("-0.05"))
        card = FindingCard(finding)
        labels = card.findChildren(QLabel)
        self.assertTrue(all(item.textFormat() == Qt.TextFormat.PlainText for item in labels))
        self.assertIn("−$0.05/board", card.details.text())
        self.assertEqual(card.findChildren(QPushButton), [])  # no zoom button until it exists
        located = []
        with_hook = FindingCard(finding, locate=located.append)
        with_hook.findChildren(QPushButton)[0].click()
        self.assertEqual(located, [("R1",)])
        self.assertFalse(self.window.can_zoom())
        card.deleteLater()
        with_hook.deleteLater()


@unittest.skipIf(QApplication is None, "Install the pinned Qt UI dependency")
class SetupUsabilityTests(unittest.TestCase):
    """Non-demo launches: what a real user sees before and after Setup."""
    @classmethod
    def setUpClass(cls):
        cls.app = QApplication.instance() or QApplication([])

    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.config = Path(self.temp.name)

    def launch(self, accept=None, check_startup=None):
        """Launch without Setup; accept=True/False then opens Setup once like a click."""
        from PySide6.QtWidgets import QDialog
        from velatrace import ui
        code = QDialog.DialogCode.Accepted if accept else QDialog.DialogCode.Rejected
        self.dialogs = []
        def dialog_exec(dialog):
            self.dialogs.append(dialog)
            return code
        # Hermetic: a developer's VELATRACE_* router variables must not leak in.
        clean = {key: value for key, value in os.environ.items() if not key.startswith("VELATRACE_")}
        with patch.dict(os.environ, clean, clear=True), \
                patch.object(ui.SettingsDialog, "exec", dialog_exec), \
                patch.object(ui.Freerouting, "check_startup", check_startup or (lambda router: None)):
            window = MainWindow(config_dir=self.config)
            window.show()
            self.settle(window)
            if accept is not None:
                window.configure()
                self.settle(window)
        self.addCleanup(self.shut, window)
        return window

    def settle(self, window):
        self.app.processEvents()  # Let queued work (e.g. the Setup timer) start first.
        deadline = time.monotonic() + 5
        while window.worker is not None and time.monotonic() < deadline:
            self.app.processEvents()
            time.sleep(.005)
        self.app.processEvents()

    def shut(self, window):
        # A busy window refuses to close; a still-running worker aborts Qt at exit.
        self.settle(window)
        window.close()
        self.assertTrue(window.executor.wait(5000))
        self.assertTrue(window.drc_executor.wait(5000))
        # Free Qt objects on the Qt thread now; a later cyclic GC (possibly while
        # another test's threads run) must not be the one to destroy them.
        window.deleteLater()
        from PySide6.QtCore import QEvent
        self.app.sendPostedEvents(None, QEvent.Type.DeferredDelete)
        self.dialogs = []
        gc.collect()

    def test_launch_opens_no_dialog_and_audit_needs_no_setup(self):
        window = self.launch()
        self.assertEqual(self.dialogs, [])
        self.assertTrue(window.load_button.isEnabled())
        self.assertFalse(window.ready)
        self.assertIn("Click Setup", window.setup_hint.text())

    def test_saved_router_is_verified_quietly_at_launch(self):
        from velatrace.ui import Settings
        Settings(jar="C:/tools/freerouting.jar").save(self.config / "settings.json")
        checked = []
        window = self.launch(check_startup=lambda router: checked.append(router))
        self.assertEqual(self.dialogs, [])
        self.assertEqual(len(checked), 1)
        self.assertTrue(window.ready)

    def test_audit_is_usable_and_routing_lock_is_explained_before_setup(self):
        window = self.launch(accept=False)
        self.assertTrue(window.description.isEnabled())
        self.assertTrue(window.load_button.isEnabled())
        self.assertFalse(window.route_button.isEnabled())
        self.assertIn("Click Setup", window.setup_hint.text())
        window.run_command("/autoroute")
        self.app.processEvents()
        # "Ready." after a mode change must not hide why routing is locked.
        self.assertTrue(window.setup_hint.isVisibleTo(window))

    def test_failed_setup_names_the_error_and_keeps_typed_values(self):
        from velatrace.errors import CapabilityError
        def missing(router):
            raise CapabilityError("Freerouting is missing.")
        window = self.launch(accept=True, check_startup=missing)
        self.assertIn("Freerouting is missing.", window.setup_hint.text())
        self.assertFalse(window.route_button.isEnabled())
        # Values from the dialog are kept for the retry, not reset to old defaults.
        self.assertEqual(window.settings.name, "Gemini")
        self.assertTrue((self.config / "settings.json").is_file())

    def test_verified_setup_unlocks_routing(self):
        window = self.launch(accept=True)
        window.mode_buttons[__import__("velatrace.routing", fromlist=["Mode"]).Mode.ROUTING].click()
        self.settle(window)
        self.assertTrue(window.route_button.isEnabled())
        self.assertFalse(window.setup_hint.isVisibleTo(window))

    def test_settings_persist_without_the_api_key(self):
        from velatrace.ui import Settings
        path = self.config / "settings.json"
        Settings(jar="C:/tools/fr.jar", model="gemini-x", key="secret-key", cap=7).save(path)
        self.assertNotIn("secret-key", path.read_text(encoding="utf-8"))
        loaded = Settings()
        loaded.load(path)
        self.assertEqual((loaded.jar, loaded.model, loaded.cap, loaded.key), ("C:/tools/fr.jar", "gemini-x", 7, ""))
        path.write_text('{"cap": "not a number", "key": "x", "unknown": 1}', encoding="utf-8")
        damaged = Settings()
        damaged.load(path)
        self.assertEqual((damaged.cap, damaged.key), (40, ""))
        path.write_text("not json", encoding="utf-8")
        Settings().load(path)  # A damaged file never blocks launch.

    def read_fixture(self, window):
        from velatrace import ui
        fixture = Path(__file__).parent / "fixtures" / "audit" / "necessity.xml"
        window.source.setCurrentIndex(2)
        no_dialog = AssertionError("zero-setup audit must not open a dialog")
        with patch.object(ui.QFileDialog, "getOpenFileName", return_value=(str(fixture), "")), \
                patch("velatrace.ui.ask", side_effect=no_dialog) as asked, \
                patch.object(ui.QMessageBox, "exec", side_effect=no_dialog):
            window.load_design()
            self.settle(window)
        asked.assert_not_called()

    def test_zero_setup_check_shows_findings_with_no_provider_or_dialog(self):
        window = self.launch()
        self.assertEqual(window.settings.model, "")  # no provider configured at all
        self.read_fixture(window)
        self.assertEqual(self.dialogs, [])
        self.assertIsNone(window.audit)  # nothing was sent anywhere
        self.assertNotIn("Stopped", window.status.text())
        self.assertEqual([card.finding.rule for card in window.finding_cards], ["duplicate.parallel_ic"])
        self.assertIn("1 saving", window.totals.text())
        self.assertIn("nothing was sent", window.audit_step.toolTip())
        self.assertTrue(window.next_button.isEnabled())
        self.assertFalse(window.price_button.isVisibleTo(window))

    def test_logos_with_duplicate_refs_do_not_block_the_checks(self):
        from velatrace.models import DesignSnapshot, Pin
        parts = (Component("REF**", "LOGO", "Symbol:Logo", ()), Component("REF**", "LOGO", "Symbol:Logo", ()),
                 Component("U1", "MCU", "Package_QFP:LQFP-32", (Pin("1", "+3V3"), Pin("2", "GND"))))
        with patch("velatrace.ui.read_xml_netlist", return_value=DesignSnapshot(parts, "fixture")):
            window = self.launch()
            self.read_fixture(window)
        self.assertNotIn("Stopped", window.status.text())
        self.assertEqual([c.reference for c in window.audit_snapshot.components], ["U1"])
        self.assertEqual(window.finding_cards[0].finding.rule, "decoupling.missing")

    def test_explain_with_ai_without_provider_points_to_setup_without_dialog(self):
        window = self.launch()
        self.read_fixture(window)
        with patch("velatrace.ui.ask") as asked:
            window.audit_next()
        asked.assert_not_called()
        self.assertIsNone(window.audit)
        self.assertIn("Setup", window.status.text())
        self.assertEqual(len(window.finding_cards), 1)  # findings stay on screen

    def test_explain_with_ai_sends_findings_as_context_after_consent(self):
        from velatrace.audit import AuditSession
        window = self.launch()
        self.read_fixture(window)
        window.settings.model, window.settings.key = "test-model", "synthetic-key"
        with patch("velatrace.ui.ask", return_value=True) as consent, \
                patch.object(AuditSession, "infer_functions", return_value={}) as infer:
            window.audit_next()
            self.settle(window)
        consent.assert_called_once()  # the privacy notice stays on the optional path
        infer.assert_called_once()
        self.assertEqual(window.audit.findings, tuple(window.findings))
        self.assertTrue(window.description.isReadOnly())

    def test_disabled_inputs_look_disabled_and_window_is_on_screen(self):
        window = self.launch(accept=False)
        for selector in ("QCheckBox:disabled", "QLineEdit:disabled", "QTextEdit:disabled", "QPushButton#primary:disabled"):
            self.assertIn(selector, window.styleSheet())
        screen = QApplication.primaryScreen().availableGeometry()
        if window.frameGeometry().width() <= screen.width():
            self.assertLessEqual(window.frameGeometry().right(), screen.right())
        self.assertGreaterEqual(window.frameGeometry().left(), screen.left())
        self.assertIn("Ctrl+Enter", window.load_button.toolTip())


if __name__ == "__main__":
    unittest.main()
