"""Self-contained HTML audit report: inline CSS, no JS, no network. All board data is escaped."""
from __future__ import annotations

import os
import tempfile
from datetime import datetime
from decimal import Decimal
from html import escape as _esc
from pathlib import Path

from .audit_rules import summarize
from .findings import Finding, Severity
from .models import DesignSnapshot

REPO_URL = "https://github.com/F-Blaze/VelaTrace"

_SECTIONS = ((Severity.ERROR, "Errors"), (Severity.WARNING, "Warnings"),
             (Severity.SAVING, "Savings"), (Severity.INFO, "Info"))

_CSS = """
:root{--bg:#fff;--fg:#1f2328;--mut:#656d76;--line:#d0d7de;--card:#f6f8fa;
--error:#cf222e;--warning:#9a6700;--saving:#1a7f37;--info:#0969da}
@media(prefers-color-scheme:dark){:root{--bg:#0d1117;--fg:#e6edf3;--mut:#8d96a0;
--line:#30363d;--card:#161b22;--error:#ff7b72;--warning:#d29922;--saving:#3fb950;--info:#58a6ff}}
*{box-sizing:border-box}
body{margin:0 auto;max-width:60rem;padding:1.5rem 1rem;background:var(--bg);color:var(--fg);
font:15px/1.5 system-ui,-apple-system,"Segoe UI",Roboto,sans-serif}
h1{margin:0 0 .25rem;font-size:1.5rem}h2{margin:2rem 0 .5rem;font-size:1.15rem}
.meta,.fine{color:var(--mut);font-size:.85rem}
.summary{margin:1rem 0;padding:.75rem 1rem;background:var(--card);border:1px solid var(--line);
border-radius:6px;font-weight:600}
.f{margin:.5rem 0;padding:.6rem .9rem;background:var(--card);border:1px solid var(--line);
border-left:4px solid var(--c);border-radius:6px;break-inside:avoid}
.error{--c:var(--error)}.warning{--c:var(--warning)}.saving{--c:var(--saving)}.info{--c:var(--info)}
.t{font-weight:600}.row{margin-top:.25rem;font-size:.9rem}.row b{color:var(--mut);font-weight:600}
table{border-collapse:collapse;width:100%;font-size:.85rem}
th,td{text-align:left;padding:.25rem .6rem;border-bottom:1px solid var(--line)}
summary{cursor:pointer;font-weight:600}
footer{margin-top:2rem;padding-top:1rem;border-top:1px solid var(--line)}
a{color:var(--info)}
@media print{body{max-width:none;font-size:12px}.f,.summary{background:none}}
"""


def _money(value: Decimal) -> str:
    return f"{'-' if value < 0 else '+'}${abs(value):.2f}/board"


def _finding(item: Finding) -> str:
    rows = [f'<div class="t">{_esc(item.title)}</div>']
    for label, value in (("Refs", ", ".join(item.refs)), ("Nets", ", ".join(item.nets)),
                         ("Evidence", item.evidence), ("Fix", item.fix),
                         ("Cost", _money(item.cost_delta) if item.cost_delta is not None else "")):
        if value:
            rows.append(f'<div class="row"><b>{label}:</b> {_esc(value)}</div>')
    return f'<div class="f {item.severity.value}">{"".join(rows)}</div>'


def render_report(snapshot: DesignSnapshot, findings: list[Finding], *, project_name: str = "",
                  generated_at: datetime | None = None, version: str = "") -> str:
    when = (generated_at or datetime.now()).strftime("%Y-%m-%d %H:%M")
    name = project_name or (snapshot.path.stem if snapshot.path else "") or "Untitled design"
    meta = [when, f"{len(snapshot.components)} parts"] + ([f"VelaTrace {version}"] if version else [])
    body = [f"<h1>{_esc(name)} — audit report</h1>",
            f'<div class="meta">{" · ".join(_esc(m) for m in meta)}</div>',
            f'<div class="summary">{_esc(summarize(findings))}</div>']
    for severity, heading in _SECTIONS:
        group = [f for f in findings if f.severity == severity]
        if group:
            body.append(f"<h2>{heading} ({len(group)})</h2>")
            body.extend(_finding(f) for f in group)
    rows = "".join(f"<tr><td>{_esc(c.reference)}</td><td>{_esc(c.value)}</td>"
                   f"<td>{_esc(c.footprint)}</td></tr>"
                   for c in sorted(snapshot.components, key=lambda c: c.reference))
    body.append(f"<h2>Bill of materials</h2><details><summary>{len(snapshot.components)} parts"
                f"</summary><table><thead><tr><th>Ref</th><th>Value</th><th>Footprint</th></tr>"
                f"</thead><tbody>{rows}</tbody></table></details>")
    body.append(f'<footer class="fine">Generated by VelaTrace — free &amp; open source: '
                f'<a href="{REPO_URL}">{REPO_URL}</a></footer>')
    return ('<!doctype html><html lang="en"><head><meta charset="utf-8">'
            '<meta name="viewport" content="width=device-width,initial-scale=1">'
            '<meta name="color-scheme" content="light dark">'
            f"<title>{_esc(name)} — VelaTrace audit</title><style>{_CSS}</style></head>"
            f"<body>{''.join(body)}</body></html>\n")


def save_report(path: str | os.PathLike[str], html: str) -> None:
    """Write UTF-8 atomically (temp file in the same directory, then replace)."""
    target = Path(path)
    fd, temporary = tempfile.mkstemp(dir=target.parent, prefix=target.name, suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(html)
        os.replace(temporary, target)
    except BaseException:
        Path(temporary).unlink(missing_ok=True)
        raise
